server:
  port: 8999

eureka:
  instance:
    hostname: localhost


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: HotelManagement
          uri: lb://HotelManagement
          predicates:
            - Path=/user/**
        - id: ContactUs
          uri: lb://ContactUs
          predicates:
            - Path=/contact/**